// Shared course data for listing and detail pages
export const courses = [
  {
    id: 'mathematics-12',
    title: 'Mathematics Grade 12',
    description: 'Calculus, Analytical Geometry, Statistics & Probability for NSC',
    subject: 'Mathematics',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 48,
    duration: '12 months',
    teacher: 'Dr. Sarah Johnson',
    rating: 4.9,
    difficulty: 'Advanced',
    topics: [
      'Differential Calculus',
      'Integral Calculus',
      'Analytical Geometry',
      'Statistics',
      'Probability',
    ],
    aiFeatures: ['Step-by-step solutions', 'Practice problems', 'Exam preparation'],
  },
  {
    id: 'physical-science-11',
    title: 'Physical Science Grade 11',
    description: 'Physics & Chemistry concepts with practical applications',
    subject: 'Physical Science',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 42,
    duration: '12 months',
    teacher: 'Prof. Michael Chen',
    rating: 4.8,
    difficulty: 'Advanced',
    topics: ['Mechanics', 'Waves & Sound', 'Organic Chemistry', 'Chemical Change'],
    aiFeatures: ['Virtual lab', 'Formula assistant', 'Concept explanations'],
  },
  {
    id: 'life-sciences-10',
    title: 'Life Sciences Grade 10',
    description: 'Biology, Ecology & Human Body Systems',
    subject: 'Life Sciences',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 36,
    duration: '12 months',
    teacher: 'Dr. Nomsa Mthembu',
    rating: 4.9,
    difficulty: 'Intermediate',
    topics: ['Cell Biology', 'Human Biology', 'Ecology', 'Genetics'],
    aiFeatures: ['3D models', 'Interactive diagrams', 'Quiz generation'],
  },
  {
    id: 'english-12',
    title: 'English Home Language Grade 12',
    description: 'Literature Analysis, Essay Writing & Language Skills',
    subject: 'English',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 40,
    duration: '12 months',
    teacher: 'Ms. Emma Thompson',
    rating: 4.7,
    difficulty: 'Core',
    topics: ['Poetry Analysis', 'Novel Study', 'Essay Writing', 'Grammar'],
    aiFeatures: ['Writing assistant', 'Grammar checker', 'Literature analysis'],
  },
];
