// Comprehensive course data for all grades and subjects
export const courses = [
  // Grade 8 Courses
  {
    id: 'mathematics-8',
    title: 'Mathematics Grade 8',
    description: 'Foundations of Algebra, Number Systems & Basic Geometry',
    subject: 'Mathematics',
    grade: '8',
    image:
      'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 32,
    duration: '12 months',
    teacher: 'Mr. James Mitchell',
    rating: 4.8,
    difficulty: 'Foundation',
    topics: [
      'Rational Numbers',
      'Algebraic Expressions',
      'Linear Equations',
      'Geometry',
      'Data Handling',
    ],
    aiFeatures: ['Step-by-step solutions', 'Interactive graphs', 'Practice problems'],
    modules: [
      { id: 'mod-1', title: 'Rational Numbers', lessons: 8, duration: '3 weeks' },
      { id: 'mod-2', title: 'Algebraic Expressions', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Linear Equations', lessons: 8, duration: '3 weeks' },
      { id: 'mod-4', title: 'Geometry', lessons: 8, duration: '3 weeks' },
    ],
  },
  {
    id: 'english-8',
    title: 'English Home Language Grade 8',
    description: 'Reading Comprehension, Creative Writing & Grammar Fundamentals',
    subject: 'English',
    grade: '8',
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 28,
    duration: '12 months',
    teacher: 'Ms. Sarah Williams',
    rating: 4.6,
    difficulty: 'Foundation',
    topics: ['Reading Comprehension', 'Creative Writing', 'Grammar', 'Poetry', 'Drama'],
    aiFeatures: ['Writing assistant', 'Grammar checker', 'Reading analysis'],
    modules: [
      { id: 'mod-1', title: 'Reading Comprehension', lessons: 7, duration: '3 weeks' },
      { id: 'mod-2', title: 'Creative Writing', lessons: 7, duration: '3 weeks' },
      { id: 'mod-3', title: 'Grammar Fundamentals', lessons: 7, duration: '3 weeks' },
      { id: 'mod-4', title: 'Poetry & Drama', lessons: 7, duration: '3 weeks' },
    ],
  },
  {
    id: 'natural-sciences-8',
    title: 'Natural Sciences Grade 8',
    description: 'Introduction to Physics, Chemistry & Earth Sciences',
    subject: 'Natural Sciences',
    grade: '8',
    image:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 30,
    duration: '12 months',
    teacher: 'Dr. Michael Brown',
    rating: 4.7,
    difficulty: 'Foundation',
    topics: ['Matter & Materials', 'Chemical Systems', 'Mechanical Systems', 'Energy & Change'],
    aiFeatures: ['Virtual experiments', 'Formula assistant', 'Concept explanations'],
    modules: [
      { id: 'mod-1', title: 'Matter & Materials', lessons: 8, duration: '3 weeks' },
      { id: 'mod-2', title: 'Chemical Systems', lessons: 7, duration: '3 weeks' },
      { id: 'mod-3', title: 'Mechanical Systems', lessons: 8, duration: '3 weeks' },
      { id: 'mod-4', title: 'Energy & Change', lessons: 7, duration: '3 weeks' },
    ],
  },
  {
    id: 'social-sciences-8',
    title: 'Social Sciences Grade 8',
    description: 'History & Geography of South Africa and the World',
    subject: 'Social Sciences',
    grade: '8',
    image:
      'https://images.unsplash.com/photo-1472173148041-00294f0814a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 26,
    duration: '12 months',
    teacher: 'Ms. Nomsa Dlamini',
    rating: 4.5,
    difficulty: 'Foundation',
    topics: ['South African History', 'World Geography', 'Climate & Weather', 'Human Rights'],
    aiFeatures: ['Timeline creator', 'Map interactions', 'Historical analysis'],
    modules: [
      { id: 'mod-1', title: 'South African History', lessons: 7, duration: '3 weeks' },
      { id: 'mod-2', title: 'World Geography', lessons: 6, duration: '3 weeks' },
      { id: 'mod-3', title: 'Climate & Weather', lessons: 7, duration: '3 weeks' },
      { id: 'mod-4', title: 'Human Rights', lessons: 6, duration: '3 weeks' },
    ],
  },

  // Grade 9 Courses
  {
    id: 'mathematics-9',
    title: 'Mathematics Grade 9',
    description: 'Advanced Algebra, Geometry & Introduction to Functions',
    subject: 'Mathematics',
    grade: '9',
    image:
      'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 36,
    duration: '12 months',
    teacher: 'Dr. Lisa Peterson',
    rating: 4.8,
    difficulty: 'Intermediate',
    topics: ['Number Patterns', 'Functions', 'Algebraic Expressions', 'Equations', 'Geometry'],
    aiFeatures: ['Step-by-step solutions', 'Function graphing', 'Problem solving'],
    modules: [
      { id: 'mod-1', title: 'Number Patterns & Functions', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Algebraic Expressions', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Equations & Inequalities', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Geometry & Measurement', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'english-9',
    title: 'English Home Language Grade 9',
    description: 'Literature Study, Advanced Writing & Language Analysis',
    subject: 'English',
    grade: '9',
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 32,
    duration: '12 months',
    teacher: 'Mr. David Wilson',
    rating: 4.7,
    difficulty: 'Intermediate',
    topics: [
      'Literature Analysis',
      'Essay Writing',
      'Language Study',
      'Media Studies',
      'Oral Communication',
    ],
    aiFeatures: ['Writing assistant', 'Literature analysis', 'Grammar checker'],
    modules: [
      { id: 'mod-1', title: 'Literature Analysis', lessons: 8, duration: '3 weeks' },
      { id: 'mod-2', title: 'Essay Writing', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Language Study', lessons: 8, duration: '3 weeks' },
      { id: 'mod-4', title: 'Media & Communication', lessons: 8, duration: '3 weeks' },
    ],
  },
  {
    id: 'natural-sciences-9',
    title: 'Natural Sciences Grade 9',
    description: 'Advanced Physics, Chemistry & Life Sciences Concepts',
    subject: 'Natural Sciences',
    grade: '9',
    image:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 34,
    duration: '12 months',
    teacher: 'Prof. Amanda Garcia',
    rating: 4.9,
    difficulty: 'Intermediate',
    topics: ['Chemical Reactions', 'Electricity & Magnetism', 'Living Systems', 'Planet Earth'],
    aiFeatures: ['Virtual lab', 'Chemical equations', 'Interactive simulations'],
    modules: [
      { id: 'mod-1', title: 'Chemical Reactions', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Electricity & Magnetism', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Living Systems', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Planet Earth', lessons: 8, duration: '3 weeks' },
    ],
  },
  {
    id: 'social-sciences-9',
    title: 'Social Sciences Grade 9',
    description: 'Modern History, Human Geography & Economic Systems',
    subject: 'Social Sciences',
    grade: '9',
    image:
      'https://images.unsplash.com/photo-1472173148041-00294f0814a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 30,
    duration: '12 months',
    teacher: 'Dr. Thabo Molefe',
    rating: 4.6,
    difficulty: 'Intermediate',
    topics: ['Industrial Revolution', 'Urbanization', 'Development Geography', 'Economic Systems'],
    aiFeatures: ['Timeline creator', 'Geographic analysis', 'Economic models'],
    modules: [
      { id: 'mod-1', title: 'Industrial Revolution', lessons: 8, duration: '3 weeks' },
      { id: 'mod-2', title: 'Urbanization', lessons: 7, duration: '3 weeks' },
      { id: 'mod-3', title: 'Development Geography', lessons: 8, duration: '3 weeks' },
      { id: 'mod-4', title: 'Economic Systems', lessons: 7, duration: '3 weeks' },
    ],
  },

  // Grade 10 Courses
  {
    id: 'mathematics-10',
    title: 'Mathematics Grade 10',
    description: 'Functions, Trigonometry & Analytical Geometry',
    subject: 'Mathematics',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 40,
    duration: '12 months',
    teacher: 'Dr. Robert Taylor',
    rating: 4.9,
    difficulty: 'Advanced',
    topics: [
      'Number Patterns',
      'Functions',
      'Finance & Growth',
      'Trigonometry',
      'Analytical Geometry',
    ],
    aiFeatures: ['Graphing calculator', 'Step-by-step solutions', 'Financial modeling'],
    modules: [
      { id: 'mod-1', title: 'Number Patterns & Functions', lessons: 10, duration: '3 weeks' },
      { id: 'mod-2', title: 'Finance & Growth', lessons: 10, duration: '3 weeks' },
      { id: 'mod-3', title: 'Trigonometry', lessons: 10, duration: '3 weeks' },
      { id: 'mod-4', title: 'Analytical Geometry', lessons: 10, duration: '3 weeks' },
    ],
  },
  {
    id: 'physical-sciences-10',
    title: 'Physical Sciences Grade 10',
    description: 'Mechanics, Waves & Atomic Theory',
    subject: 'Physical Sciences',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 38,
    duration: '12 months',
    teacher: 'Prof. Maria Rodriguez',
    rating: 4.8,
    difficulty: 'Advanced',
    topics: ['Mechanics', 'Waves & Sound', 'Atomic Theory', 'Chemical Bonding'],
    aiFeatures: ['Virtual lab', 'Physics simulations', 'Chemical structures'],
    modules: [
      { id: 'mod-1', title: 'Mechanics', lessons: 10, duration: '3 weeks' },
      { id: 'mod-2', title: 'Waves & Sound', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Atomic Theory', lessons: 10, duration: '3 weeks' },
      { id: 'mod-4', title: 'Chemical Bonding', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'life-sciences-10',
    title: 'Life Sciences Grade 10',
    description: 'Biology, Ecology & Human Body Systems',
    subject: 'Life Sciences',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 36,
    duration: '12 months',
    teacher: 'Dr. Nomsa Mthembu',
    rating: 4.9,
    difficulty: 'Intermediate',
    topics: ['Cell Biology', 'Human Biology', 'Ecology', 'Genetics'],
    aiFeatures: ['3D models', 'Interactive diagrams', 'Quiz generation'],
    modules: [
      { id: 'mod-1', title: 'Cell Biology', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Human Biology', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Ecology', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Genetics', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'english-10',
    title: 'English Home Language Grade 10',
    description: 'Literature Study, Creative Writing & Language Skills',
    subject: 'English',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 34,
    duration: '12 months',
    teacher: 'Ms. Jennifer Clark',
    rating: 4.7,
    difficulty: 'Advanced',
    topics: ['Poetry Analysis', 'Novel Study', 'Drama', 'Essay Writing', 'Language Study'],
    aiFeatures: ['Writing assistant', 'Literature analysis', 'Grammar checker'],
    modules: [
      { id: 'mod-1', title: 'Poetry Analysis', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Novel Study', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Drama Study', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Essay Writing', lessons: 8, duration: '3 weeks' },
    ],
  },
  {
    id: 'history-10',
    title: 'History Grade 10',
    description: 'World History: Ancient Civilizations to Modern Times',
    subject: 'History',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1472173148041-00294f0814a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 32,
    duration: '12 months',
    teacher: 'Dr. Kenneth Adams',
    rating: 4.6,
    difficulty: 'Advanced',
    topics: ['Ancient Civilizations', 'Medieval Period', 'Renaissance', 'Modern History'],
    aiFeatures: ['Timeline creator', 'Historical analysis', 'Document analysis'],
    modules: [
      { id: 'mod-1', title: 'Ancient Civilizations', lessons: 8, duration: '3 weeks' },
      { id: 'mod-2', title: 'Medieval Period', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Renaissance', lessons: 8, duration: '3 weeks' },
      { id: 'mod-4', title: 'Modern History', lessons: 8, duration: '3 weeks' },
    ],
  },
  {
    id: 'geography-10',
    title: 'Geography Grade 10',
    description: 'Physical Geography & Human Settlement Patterns',
    subject: 'Geography',
    grade: '10',
    image:
      'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 30,
    duration: '12 months',
    teacher: 'Ms. Rebecca Johnson',
    rating: 4.5,
    difficulty: 'Advanced',
    topics: ['Landforms', 'Climate Systems', 'Population Studies', 'Settlement Geography'],
    aiFeatures: ['Interactive maps', 'Climate modeling', 'Population analysis'],
    modules: [
      { id: 'mod-1', title: 'Landforms & Processes', lessons: 8, duration: '3 weeks' },
      { id: 'mod-2', title: 'Climate Systems', lessons: 7, duration: '3 weeks' },
      { id: 'mod-3', title: 'Population Studies', lessons: 8, duration: '3 weeks' },
      { id: 'mod-4', title: 'Settlement Geography', lessons: 7, duration: '3 weeks' },
    ],
  },

  // Grade 11 Courses
  {
    id: 'mathematics-11',
    title: 'Mathematics Grade 11',
    description: 'Advanced Functions, Statistics & Trigonometry',
    subject: 'Mathematics',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 44,
    duration: '12 months',
    teacher: 'Dr. Patricia Evans',
    rating: 4.9,
    difficulty: 'Advanced',
    topics: ['Functions', 'Trigonometry', 'Euclidean Geometry', 'Statistics', 'Probability'],
    aiFeatures: ['Advanced graphing', 'Statistical analysis', 'Geometric proofs'],
    modules: [
      { id: 'mod-1', title: 'Functions & Relations', lessons: 11, duration: '3 weeks' },
      { id: 'mod-2', title: 'Trigonometry', lessons: 11, duration: '3 weeks' },
      { id: 'mod-3', title: 'Euclidean Geometry', lessons: 11, duration: '3 weeks' },
      { id: 'mod-4', title: 'Statistics & Probability', lessons: 11, duration: '3 weeks' },
    ],
  },
  {
    id: 'physical-science-11',
    title: 'Physical Science Grade 11',
    description: 'Physics & Chemistry concepts with practical applications',
    subject: 'Physical Science',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 42,
    duration: '12 months',
    teacher: 'Prof. Michael Chen',
    rating: 4.8,
    difficulty: 'Advanced',
    topics: ['Mechanics', 'Waves & Sound', 'Organic Chemistry', 'Chemical Change'],
    aiFeatures: ['Virtual lab', 'Formula assistant', 'Concept explanations'],
    modules: [
      { id: 'mod-1', title: 'Mechanics & Dynamics', lessons: 11, duration: '3 weeks' },
      { id: 'mod-2', title: 'Waves & Sound', lessons: 10, duration: '3 weeks' },
      { id: 'mod-3', title: 'Organic Chemistry', lessons: 11, duration: '3 weeks' },
      { id: 'mod-4', title: 'Chemical Change', lessons: 10, duration: '3 weeks' },
    ],
  },
  {
    id: 'life-sciences-11',
    title: 'Life Sciences Grade 11',
    description: 'Advanced Biology, Genetics & Human Physiology',
    subject: 'Life Sciences',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 40,
    duration: '12 months',
    teacher: 'Dr. Sarah Thompson',
    rating: 4.8,
    difficulty: 'Advanced',
    topics: ['Biodiversity', 'Body Systems', 'Genetics', 'Evolution'],
    aiFeatures: ['3D anatomy models', 'Genetic simulations', 'Interactive diagrams'],
    modules: [
      { id: 'mod-1', title: 'Biodiversity & Classification', lessons: 10, duration: '3 weeks' },
      { id: 'mod-2', title: 'Body Systems', lessons: 10, duration: '3 weeks' },
      { id: 'mod-3', title: 'Genetics & Inheritance', lessons: 10, duration: '3 weeks' },
      { id: 'mod-4', title: 'Evolution & Natural Selection', lessons: 10, duration: '3 weeks' },
    ],
  },
  {
    id: 'english-11',
    title: 'English Home Language Grade 11',
    description: 'Advanced Literature Analysis & Creative Writing',
    subject: 'English',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 38,
    duration: '12 months',
    teacher: 'Ms. Laura Mitchell',
    rating: 4.7,
    difficulty: 'Advanced',
    topics: ['Poetry Analysis', 'Novel Study', 'Drama', 'Creative Writing', 'Media Studies'],
    aiFeatures: ['Writing assistant', 'Literature analysis', 'Creative prompts'],
    modules: [
      { id: 'mod-1', title: 'Poetry & Literary Devices', lessons: 10, duration: '3 weeks' },
      { id: 'mod-2', title: 'Novel Analysis', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Drama Study', lessons: 10, duration: '3 weeks' },
      { id: 'mod-4', title: 'Creative Writing', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'history-11',
    title: 'History Grade 11',
    description: 'South African History & Global Perspectives',
    subject: 'History',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1472173148041-00294f0814a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 36,
    duration: '12 months',
    teacher: 'Dr. Mandla Nkomo',
    rating: 4.6,
    difficulty: 'Advanced',
    topics: ['Colonialism', 'Apartheid', 'Liberation Movements', 'Global History'],
    aiFeatures: ['Document analysis', 'Timeline creator', 'Historical perspectives'],
    modules: [
      { id: 'mod-1', title: 'Colonialism in Africa', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Apartheid System', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Liberation Movements', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Global Historical Context', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'geography-11',
    title: 'Geography Grade 11',
    description: 'Human Geography & Environmental Studies',
    subject: 'Geography',
    grade: '11',
    image:
      'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 34,
    duration: '12 months',
    teacher: 'Ms. Catherine Lee',
    rating: 4.5,
    difficulty: 'Advanced',
    topics: ['Climate Change', 'Urban Geography', 'Rural Development', 'Environmental Issues'],
    aiFeatures: ['Climate modeling', 'Urban planning tools', 'Environmental analysis'],
    modules: [
      { id: 'mod-1', title: 'Climate & Weather Systems', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Urban Geography', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Rural Development', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Environmental Management', lessons: 8, duration: '3 weeks' },
    ],
  },

  // Grade 12 Courses
  {
    id: 'mathematics-12',
    title: 'Mathematics Grade 12',
    description: 'Calculus, Analytical Geometry, Statistics & Probability for NSC',
    subject: 'Mathematics',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 48,
    duration: '12 months',
    teacher: 'Dr. Sarah Johnson',
    rating: 4.9,
    difficulty: 'Advanced',
    topics: [
      'Differential Calculus',
      'Integral Calculus',
      'Analytical Geometry',
      'Statistics',
      'Probability',
    ],
    aiFeatures: ['Step-by-step solutions', 'Practice problems', 'Exam preparation'],
    modules: [
      { id: 'mod-1', title: 'Differential Calculus', lessons: 12, duration: '3 weeks' },
      { id: 'mod-2', title: 'Integral Calculus', lessons: 12, duration: '3 weeks' },
      { id: 'mod-3', title: 'Analytical Geometry', lessons: 12, duration: '3 weeks' },
      { id: 'mod-4', title: 'Statistics & Probability', lessons: 12, duration: '3 weeks' },
    ],
  },
  {
    id: 'physical-sciences-12',
    title: 'Physical Sciences Grade 12',
    description: 'Advanced Physics & Chemistry for NSC Examinations',
    subject: 'Physical Sciences',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 46,
    duration: '12 months',
    teacher: 'Prof. Andrew Wilson',
    rating: 4.9,
    difficulty: 'Advanced',
    topics: [
      'Mechanics',
      'Waves & Sound',
      'Electricity & Magnetism',
      'Organic Chemistry',
      'Physical Chemistry',
    ],
    aiFeatures: ['Virtual laboratory', 'Formula database', 'Exam simulations'],
    modules: [
      { id: 'mod-1', title: 'Mechanics & Dynamics', lessons: 12, duration: '3 weeks' },
      { id: 'mod-2', title: 'Waves & Electricity', lessons: 11, duration: '3 weeks' },
      { id: 'mod-3', title: 'Organic Chemistry', lessons: 12, duration: '3 weeks' },
      { id: 'mod-4', title: 'Physical Chemistry', lessons: 11, duration: '3 weeks' },
    ],
  },
  {
    id: 'life-sciences-12',
    title: 'Life Sciences Grade 12',
    description: 'Advanced Biology, Genetics & Human Impact Studies',
    subject: 'Life Sciences',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 44,
    duration: '12 months',
    teacher: 'Dr. Rachel Green',
    rating: 4.8,
    difficulty: 'Advanced',
    topics: [
      'DNA & Protein Synthesis',
      'Meiosis & Genetics',
      'Evolution',
      'Human Impact on Environment',
    ],
    aiFeatures: ['3D molecular models', 'Genetic calculators', 'Ecosystem simulations'],
    modules: [
      { id: 'mod-1', title: 'DNA & Protein Synthesis', lessons: 11, duration: '3 weeks' },
      { id: 'mod-2', title: 'Meiosis & Genetics', lessons: 11, duration: '3 weeks' },
      { id: 'mod-3', title: 'Evolution & Speciation', lessons: 11, duration: '3 weeks' },
      { id: 'mod-4', title: 'Human Environmental Impact', lessons: 11, duration: '3 weeks' },
    ],
  },
  {
    id: 'english-12',
    title: 'English Home Language Grade 12',
    description: 'Literature Analysis, Essay Writing & Language Skills',
    subject: 'English',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 40,
    duration: '12 months',
    teacher: 'Ms. Emma Thompson',
    rating: 4.7,
    difficulty: 'Core',
    topics: ['Poetry Analysis', 'Novel Study', 'Essay Writing', 'Grammar'],
    aiFeatures: ['Writing assistant', 'Grammar checker', 'Literature analysis'],
    modules: [
      { id: 'mod-1', title: 'Poetry Analysis', lessons: 10, duration: '3 weeks' },
      { id: 'mod-2', title: 'Novel Study', lessons: 10, duration: '3 weeks' },
      { id: 'mod-3', title: 'Essay Writing', lessons: 10, duration: '3 weeks' },
      { id: 'mod-4', title: 'Language & Grammar', lessons: 10, duration: '3 weeks' },
    ],
  },
  {
    id: 'history-12',
    title: 'History Grade 12',
    description: 'Modern History & NSC Examination Preparation',
    subject: 'History',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1472173148041-00294f0814a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 42,
    duration: '12 months',
    teacher: 'Dr. Vincent Kumar',
    rating: 4.6,
    difficulty: 'Advanced',
    topics: ['Cold War', 'Decolonization', 'Civil Rights Movements', 'Modern South Africa'],
    aiFeatures: ['Document analysis', 'Essay structuring', 'Historical timelines'],
    modules: [
      { id: 'mod-1', title: 'Cold War Era', lessons: 11, duration: '3 weeks' },
      { id: 'mod-2', title: 'Decolonization in Africa', lessons: 10, duration: '3 weeks' },
      { id: 'mod-3', title: 'Civil Rights Movements', lessons: 11, duration: '3 weeks' },
      { id: 'mod-4', title: 'Modern South Africa', lessons: 10, duration: '3 weeks' },
    ],
  },
  {
    id: 'geography-12',
    title: 'Geography Grade 12',
    description: 'Advanced Human Geography & Environmental Management',
    subject: 'Geography',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 38,
    duration: '12 months',
    teacher: 'Ms. Diana Foster',
    rating: 4.5,
    difficulty: 'Advanced',
    topics: [
      'Rural & Urban Settlement',
      'Economic Geography',
      'Development Geography',
      'Environmental Management',
    ],
    aiFeatures: ['GIS mapping', 'Development indicators', 'Environmental modeling'],
    modules: [
      { id: 'mod-1', title: 'Settlement Geography', lessons: 10, duration: '3 weeks' },
      { id: 'mod-2', title: 'Economic Geography', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Development Studies', lessons: 10, duration: '3 weeks' },
      { id: 'mod-4', title: 'Environmental Management', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'accounting-12',
    title: 'Accounting Grade 12',
    description: 'Financial Accounting & Business Management',
    subject: 'Accounting',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1554224155-6726b3ff858f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 36,
    duration: '12 months',
    teacher: 'Mr. James Roberts',
    rating: 4.7,
    difficulty: 'Advanced',
    topics: [
      'Financial Statements',
      'Manufacturing',
      'Company Financial Statements',
      'Financial Analysis',
    ],
    aiFeatures: ['Financial calculators', 'Balance sheet tools', 'Ratio analysis'],
    modules: [
      { id: 'mod-1', title: 'Financial Statements', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Manufacturing Accounts', lessons: 9, duration: '3 weeks' },
      { id: 'mod-3', title: 'Company Accounts', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Financial Analysis', lessons: 9, duration: '3 weeks' },
    ],
  },
  {
    id: 'business-studies-12',
    title: 'Business Studies Grade 12',
    description: 'Business Management & Entrepreneurship',
    subject: 'Business Studies',
    grade: '12',
    image:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80',
    lessons: 34,
    duration: '12 months',
    teacher: 'Ms. Patricia Davis',
    rating: 4.6,
    difficulty: 'Advanced',
    topics: ['Business Management', 'Marketing', 'Human Resources', 'Financial Management'],
    aiFeatures: ['Business plan templates', 'Market analysis tools', 'Financial projections'],
    modules: [
      { id: 'mod-1', title: 'Business Management', lessons: 9, duration: '3 weeks' },
      { id: 'mod-2', title: 'Marketing Strategies', lessons: 8, duration: '3 weeks' },
      { id: 'mod-3', title: 'Human Resources', lessons: 9, duration: '3 weeks' },
      { id: 'mod-4', title: 'Financial Management', lessons: 8, duration: '3 weeks' },
    ],
  },
];

// Sample lesson data for course details
export const sampleLessons = [
  {
    id: 'lesson-1',
    title: 'Introduction to Differential Calculus',
    description: 'Learn the fundamentals of derivatives and their applications',
    duration: '45 minutes',
    videoUrl: 'https://www.youtube.com/embed/WUvTyaaNkzM',
    resources: [
      { type: 'PDF', title: 'Calculus Notes', url: '#' },
      { type: 'Practice', title: 'Derivative Exercises', url: '#' },
      { type: 'Quiz', title: 'Understanding Derivatives', url: '#' },
    ],
    completed: false,
  },
  {
    id: 'lesson-2',
    title: 'The Chain Rule',
    description: 'Master the chain rule for composite functions',
    duration: '40 minutes',
    videoUrl: 'https://www.youtube.com/embed/H-ybCx8gt-8',
    resources: [
      { type: 'PDF', title: 'Chain Rule Examples', url: '#' },
      { type: 'Practice', title: 'Chain Rule Problems', url: '#' },
      { type: 'Video', title: 'Additional Examples', url: '#' },
    ],
    completed: true,
  },
  {
    id: 'lesson-3',
    title: 'Applications of Derivatives',
    description: 'Real-world applications of calculus in optimization',
    duration: '50 minutes',
    videoUrl: 'https://www.youtube.com/embed/WUvTyaaNkzM',
    resources: [
      { type: 'PDF', title: 'Application Examples', url: '#' },
      { type: 'Practice', title: 'Optimization Problems', url: '#' },
      { type: 'Simulation', title: 'Interactive Graphs', url: '#' },
    ],
    completed: false,
  },
];
